services:
  vpn-server:
    container_name: vpn-server
    hostname: secretbay.me
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./certbot/conf/live/${DOMAIN}/fullchain.pem:/app/certs/server.crt:ro
      - ./certbot/conf/live/${DOMAIN}/privkey.pem:/app/certs/server.key:ro
      - ./static:/app/static
      - ./.env:/app/.env:ro
      - ./logs:/app/logs:rw
      - ./metrics:/app/metrics:rw
      - ./backups:/var/backups/vpn-server:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ENV=production
      - DOCKER_CONTAINER=true
      - SERVER_PORT=9999
      - JWT_SECRET=${JWT_SECRET:-YourSuperSecretKey-ThisIsAVeryLongSecretKeyForDevelopment-2024123123213}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - ALLOWED_ORIGINS=https://secretbay.me
      - TLS_MIN_VERSION=1.3
      - MAX_REQUEST_SIZE=1048576
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_DURATION=60
      - MAX_CONN_AGE=3600
      - READ_TIMEOUT=30
      - WRITE_TIMEOUT=30
      - HTTP2_ENABLED=true
      - HTTP2_MAX_CONCURRENT_STREAMS=250
      - HTTP2_MAX_FRAME_SIZE=16384
      - HTTP2_BUFFER_SIZE=65536
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=secretbay
      - DB_USER=secretbay
      - DB_PASSWORD=${DB_PASSWORD:-changeme}
      - TZ=UTC
    user: "${UID:-1000}:${GID:-1000}"
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - no-new-privileges:true
    networks:
      - secretbay-net
    stop_grace_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
      certbot:
        condition: service_started
    command: /app/vpn-setup-server

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - type: tmpfs
        target: /var/run
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 256M
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=2048
      - NGINX_KEEPALIVE_TIMEOUT=65
      - NGINX_HTTP2_MAX_FIELD_SIZE=16k
      - NGINX_HTTP2_MAX_HEADER_SIZE=32k
    depends_on:
      - vpn-server
      - certbot
    restart: unless-stopped
    networks:
      - secretbay-net
    stop_grace_period: 10s

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - secretbay-net
    stop_grace_period: 10s

  backup-cron:
    image: alpine:latest 
    volumes:
      - ./backups:/var/backups/vpn-server
      - ./scripts/backup-cron.sh:/tmp/backup.sh:ro
      - /tmp:/tmp
    command: sh -c "cp /tmp/backup.sh /tmp/backup-exec.sh && chmod +x /tmp/backup-exec.sh && crond -f"
    environment:
      - BACKUP_SCHEDULE=0 0 * * * /tmp/backup-exec.sh
    restart: unless-stopped
    networks:
      - secretbay-net
    stop_grace_period: 5s

  postgres:
    image: postgres:16-alpine
    container_name: secretbay-db
    environment:
      - POSTGRES_DB=secretbay
      - POSTGRES_USER=secretbay
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - secretbay-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secretbay"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  secretbay-net:
    driver: bridge
    name: secretbay-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"