version: '3.8'

services:
  vpn-server:
    hostname: Secretbay.me
    build: .
    ports:
      - "9999:9999"  # Removed 443 since nginx handles SSL
    volumes:
      - ./certs:/app/certs:ro
      - ./certs/server.crt:/app/server.crt:ro    
      - ./certs/server.key:/app/server.key:ro    
      - ./static:/app/static
      - ./.env:/app/.env:ro
    environment:
      - SERVER_PORT=9999
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Changed from 8443 to 443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - vpn-server
    restart: unless-stopped
    # Add dhparam generation on container start if file doesn't exist
    entrypoint: >
      /bin/sh -c "
      if [ ! -f /etc/nginx/certs/dhparam.pem ]; then
        echo 'Generating DHParam file...'
        openssl dhparam -out /etc/nginx/certs/dhparam.pem 2048
      fi &&
      nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
    entrypoint: >
      sh -c "while :; do
              certbot renew --quiet --deploy-hook 'nginx -s reload' --disable-hook-validation;
              sleep 12h;
            done"