services:
  vpn-server:
    container_name: vpn-server
    hostname: secretbay.me
    build: .
    ports:
      - "9999:9999"
    volumes:
      - ./server.crt:/app/certs/server.crt:ro
      - ./server.key:/app/certs/server.key:ro
      - ./static:/app/static
      - ./.env:/app/.env:ro
      - ./logs:/app/logs:rw
      - ./metrics:/app/metrics:rw
      - ./backups:/var/backups/vpn-server:rw
    environment:
      - ENV=production
      - DOCKER_CONTAINER=true
      - SERVER_PORT=9999
      - JWT_SECRET=${JWT_SECRET:-YourSuperSecretKey-ThisIsAVeryLongSecretKeyForDevelopment-2024123123213}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - ALLOWED_ORIGINS=https://secretbay.me
      - TLS_MIN_VERSION=1.3
      - MAX_REQUEST_SIZE=1048576
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_DURATION=60
      - MAX_CONN_AGE=3600
      - READ_TIMEOUT=30
      - WRITE_TIMEOUT=30
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - no-new-privileges:true
    networks:
      - secretbay-net
    stop_grace_period: 30s
    depends_on: []

  nginx:
    container_name: nginx  # Added explicit container name
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - ./certbot/conf/live/${DOMAIN}/chain.pem:/etc/nginx/ssl/chain.pem:ro
    depends_on:
      vpn-server:
        condition: service_started
    restart: unless-stopped
    networks:
      - secretbay-net
    stop_grace_period: 10s

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - secretbay-net
    stop_grace_period: 10s

  backup-cron:
    image: alpine:latest 
    volumes:
      - ./backups:/var/backups/vpn-server
      - ./scripts/backup-cron.sh:/tmp/backup.sh:ro
      - /tmp:/tmp
    command: sh -c "cp /tmp/backup.sh /tmp/backup-exec.sh && chmod +x /tmp/backup-exec.sh && crond -f"
    environment:
      - BACKUP_SCHEDULE=0 0 * * * /tmp/backup-exec.sh
    restart: unless-stopped
    networks:
      - secretbay-net
    stop_grace_period: 5s

networks:
  secretbay-net:
    driver: bridge
    name: secretbay-net