version: '3.8'

services:
  vpn-server:
    build: .
    ports:
      - "443:443"
      - "9999:9999"
    volumes:
      - ./certs:/app/certs
      - ./static:/app/static
    environment:
      - SERVER_PORT=9999
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    depends_on:
      - vpn-server
    restart: unless-stopped