version: '3.8'

services:
  vpn-server:
    build: .
    ports:
      - "443:443"
      - "9999:9999"
    volumes:
      - ./certs:/app/certs:ro
      - ./static:/app/static
    environment:
      - SERVER_PORT=9999
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
    restart: unless-stopped

  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./static:/usr/share/nginx/html
        - ./certs:/etc/nginx/certs:ro
      depends_on:
        - vpn-server
      restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-logs:/var/log/letsencrypt
    entrypoint: >
      sh -c "while :; do
              certbot renew --quiet --deploy-hook 'nginx -s reload';
              sleep 12h;
            done"