services:
  vpn-server:
    hostname: Secretbay.me
    build: .
    ports:
      - "9999:9999" 
    volumes:
      - ./certs:/app/certs:ro
      - ./certs/server.crt:/app/server.crt:ro    
      - ./certs/server.key:/app/server.key:ro    
      - ./static:/app/static
      - ./.env:/app/.env:ro
    environment:
      - ENV=production
      - DOCKER_CONTAINER=true
      - SERVER_PORT=9999
      - JWT_SECRET=${JWT_SECRET:-YourSuperSecretKey-ThisIsAVeryLongSecretKeyForDevelopment-2024123123213}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - ALLOWED_ORIGINS=https://secretbay.me,https://www.secretbay.me
      - TLS_MIN_VERSION=1.2
      - MAX_REQUEST_SIZE=1048576
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_DURATION=60
      - MAX_CONN_AGE=3600
      - READ_TIMEOUT=30
      - WRITE_TIMEOUT=30
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
    depends_on:
      - vpn-server
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@secretbay.me --agree-tos --no-eff-email --staging -d secretbay.me -d www.secretbay.me
    depends_on:
      - nginx